language: python

cache: pip

dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1.5

install:
  - pip install -U pip
  - pip install -r requirements-ci.txt
  - pip install django==$DJANGO_VERSION

script:
  - pytest

before_deploy:
  # PyPI deploy fails if there are unstaged changes
  # Reset any unstaged changes (such as updates to Pipfile or Pipfile.lock)
  - git checkout -- .

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  username: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
    # deploy only once
    python: "3.7"
    condition: "$DJANGO_VERSION = 2.1.5"
